version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: core.containerfile
    container_name: switchmap-core
    user: "${API_UID}:${API_GID}"
    volumes:
      - .:/home/switchmap-core/core
      - /home/switchmap-core/core/.venv
    environment:
      - PYTHONUNBUFFERED=1
      - POLLER_API_URL=http://poller:7000/send-data  # Core will receive SNMP data from Poller
    networks:
      - switchmap-network
    command: ["python", "-m", "switchmap.core"]

networks:
  switchmap-network:
    driver: bridge
