version: "3.8"

services:
  poller:
    build:
      context: .
      dockerfile: poller.containerfile
    container_name: switchmap-poller
    user: "${API_UID}:${API_GID}"
    volumes:
      - .:/home/switchmap-poller/poller
      - /home/switchmap-poller/poller/.venv
    environment:
      - PYTHONUNBUFFERED=1
      - CORE_API_URL=http://core:7000/process-data  # Poller will send SNMP data to Core
    networks:
      - switchmap-network
    command: ["python", "-m", "switchmap.poller"]

networks:
  switchmap-network:
    driver: bridge
