version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: core.containerfile
    container_name: switchmap-core
    user: "${API_UID}:${API_GID}"
    volumes:
      - .:/home/switchmap-core/core
      - /home/switchmap-core/core/.venv
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/switchmap
      - API_URL=http://server:7000/graphql
    depends_on:
    networks:
      - switchmap-network


networks:
  switchmap-network:
    driver: bridge
