name: Build Python Docs

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
          pip install -r requirements.txt
      - name: Generate Documentation
        run: |
          sphinx-apidoc -o docs/source/ .
          cd docs && make html
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-html
          path: docs/_build/html
